@baseUrl = http://localhost:3000
@adminEmail = admin@demo.com
@userEmail = usuario@demo.com
@validPasswordUser = 123456  
@validPasswordAdmin = admin123       
@invalidPassword = 1234567
@unknownEmail = noexiste@test.com

### LOGIN OK - admin (200)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{validPasswordAdmin}}"
}

### LOGIN OK - user (200)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{userEmail}}",
  "password": "{{validPasswordUser}}"
}

### LOGIN FAIL - wrong password (401)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{userEmail}}",
  "password": "{{invalidPassword}}"
}

### LOGIN FAIL - unknown email (401)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{unknownEmail}}",
  "password": "{{validPasswordUser}}"
}

### LOGIN FAIL - invalid payload: password too short (400)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{userEmail}}",
  "password": "123"
}

### LOGIN FAIL - invalid payload: bad email format (400)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "email-invalido",
  "password": "{{validPasswordUser}}"
}
