const DEFAULT_NEWS_EXCERPT_MAX_LENGTH = 180;

function normalizeNewsText(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

export function buildNewsExcerptFromContent(
  content: string,
  maxLength = DEFAULT_NEWS_EXCERPT_MAX_LENGTH,
): string {
  const normalizedContent = normalizeNewsText(content);

  if (!normalizedContent) {
    return '';
  }

  if (normalizedContent.length <= maxLength) {
    return normalizedContent;
  }

  const tentativeExcerpt = normalizedContent.slice(0, maxLength + 1).trim();
  const lastSpaceIndex = tentativeExcerpt.lastIndexOf(' ');
  const cutIndex =
    lastSpaceIndex >= Math.floor(maxLength * 0.6)
      ? lastSpaceIndex
      : maxLength;

  return `${tentativeExcerpt.slice(0, cutIndex).trim()}...`;
}

export function isAutoGeneratedNewsExcerpt(
  excerpt: string,
  content: string,
): boolean {
  return (
    normalizeNewsText(excerpt) === buildNewsExcerptFromContent(content)
  );
}

export function resolveNewsExcerpt(excerpt: string, content: string): string {
  const normalizedExcerpt = normalizeNewsText(excerpt);

  if (normalizedExcerpt) {
    return normalizedExcerpt;
  }

  return buildNewsExcerptFromContent(content);
}
